apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ingress
  namespace: ops
spec:
  ingressClassName: test-mse
  rules:
    - host: flask.sieredu.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: flask-svc
                port:
                  number: 80

  tls:
    - hosts:
        - flask.sieredu.com
      secretName: ops-ingress-tls

---
apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: ops
  labels:
    app: flask
spec:
  selector:
    app: flask
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: ops
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: ${IMAGE}
          ports:
            - name: service-port
              containerPort: 8000

